# Generated by Django 5.2.12 on 2026-05-20 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_clientes_delete_cliente'),
        ('planes_separe', '0004_detalleplansepare'),
        ('productos', '0003_productotalla'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cambios',
            fields=[
                ('id_cambio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cambio', models.DateTimeField()),
                ('total_diferencia', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('id_cliente', models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.clientes')),
                ('id_plan_separe', models.ForeignKey(blank=True, db_column='id_plan_separe', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='planes_separe.planessepare')),
                ('id_venta', models.ForeignKey(blank=True, db_column='id_venta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.ventas')),
            ],
            options={
                'db_table': 'cambios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleCambioEntrada',
            fields=[
                ('id_detalle_entrada', models.AutoField(primary_key=True, serialize=False)),
                ('talla', models.CharField(max_length=10)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_cambio', models.ForeignKey(db_column='id_cambio', on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='cambios.cambios')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.productos')),
            ],
            options={
                'db_table': 'detalle_cambio_entrada',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleCambioSalida',
            fields=[
                ('id_detalle_salida', models.AutoField(primary_key=True, serialize=False)),
                ('talla', models.CharField(max_length=10)),
                ('cantidad', models.IntegerField()),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_cambio', models.ForeignKey(db_column='id_cambio', on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='cambios.cambios')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.productos')),
            ],
            options={
                'db_table': 'detalle_cambio_salida',
                'managed': True,
            },
        ),
    ]
