# Generated by Django 6.0.3 on 2026-03-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes_separe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregas',
            fields=[
                ('id_entrega', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'entregas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanesSepare',
            fields=[
                ('id_plan_separe', models.AutoField(primary_key=True, serialize=False)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('anticipo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('saldo_restante', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'planes_separe',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='PlanSepare',
        ),
    ]
