# Generated by Django 5.2.12 on 2026-03-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes_separe', '0003_auto_20260329_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePlanSepare',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('talla', models.CharField(max_length=10)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'detalle_plan_separe',
                'managed': False,
            },
        ),
    ]
