# Generated by Django 5.2.12 on 2026-03-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_kardex_productos_remove_producto_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoTalla',
            fields=[
                ('id_talla', models.AutoField(primary_key=True, serialize=False)),
                ('talla', models.CharField(max_length=10)),
                ('cantidad', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'producto_tallas',
                'managed': False,
            },
        ),
    ]
